### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by ducaale** [ducaale/xh#1]
I was made aware [1] the name Yahc might be confused with a rust community member who goes by the name [Yaahc](https://github.com/yaahc). Therefore I am planning to rename this project using one of the following:
* **ht**: This would have been the best pick, but it is already being used by a similar project https://github.com/mark-burnett/ht
* **rq**: This name is being used by a popular python [job queue library](https://github.com/rq/rq). Although it is possible to append `-rs` at the end to avoid a name clash.
* **htyr**: Not sure what it means but for some reason I like it.

[1] https://www.reddit.com/r/rust/comments/k0aika/yahc_yet_another_httpie_clone_in_rust/gdgza01?utm_source=share&utm_medium=web2x&context=3

**Comment by andresv** [comment]
It seems that https://github.com/mark-burnett/ht is unmaintained. Maybe it is still possible to use the same name if those projects can be merged.

**Comment by mark-burnett** [comment]
I'd be happy to transfer the name.  I definitely didn't intend to name squat `ht`, and would be happy for it to be taken over by this project :)

**Comment by ducaale** [comment]
@mark-burnett Thank you very much for entrusting the name `ht` to this project! I will start the process of renaming `yahc` shortly.

As for transferring the [crate name](https://github.com/mark-burnett/ht), I think it would be more involved but still [doable](https://crates.io/policies#package-ownership).

**Comment by ducaale** [comment]
`yahc` has been renamed to `ht` and the crate name transfer is now complete 🎉.

Thanks to @mark-burnett for agreeing to transfer the name and @andresv for initiating the conversation.

**Comment by NBonaparte** [comment]
If you're not aware, `/usr/bin/ht` is also used for a TeXLive program (Debian: [texlive-plain-generic](https://packages.debian.org/buster/all/texlive-plain-generic/filelist), Arch: [texlive-core](https://archlinux.org/packages/extra/any/texlive-core/files/)) and causes a collision when installing ([AUR comment](https://aur.archlinux.org/packages/ht-rs/#comment-788509)).

**Comment by mehcode** [comment]
As a random passerby (cool project btw), I vote for `xh` or "eXtra Http". Some quick searching doesn't seem to show it existing.

**Comment by kpcyrd** [comment]
hey, debian maintainer here, there's a policy in debian that no two packages are allowed to install a binary with an identical name so we'd need to rename it there too. You can research if the name is already taken using the search:

https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=contents&keywords=usr%2Fbin%2Fht

(you might need to check all of `usr/bin/foo`, `usr/sbin/foo`, `bin/foo` and `sbin/foo`)

**Comment by ducaale** [comment]
Thanks, @kpcyrd, would it be possible to do something similar to the [ht](https://archlinux.org/packages/community/x86_64/ht/) package in Arch, i.e `apt install ht` which installs a binary named `ht-rust`? I think [bat](https://github.com/sharkdp/bat#on-ubuntu-using-apt) does something similar.

**Comment by anthraxx** [comment]
I think this is a horrible hack and not a solution. Upstream should at best provide a unique name for the binaries which is defined upstream. this would also create diversity in which binary is being called when ht is installed using cargo. A uniform experience should be the goal of a CLI tool.

**Comment by ducaale** [comment]
Although I'm very of the name `ht`, I am open to the idea of renaming `ht` to a different name. I am saying this because it would become harder as the number of places `ht` is published increases. Some of the names that come to my mind include:
* `rq`:  stands for request
* `hr`: stands for http-request
* `xh` which was suggested by @mehcode

**Comment by blyxxyz** [comment]
`rq` is taken by [`python3-rq`/Redis Queue](https://packages.debian.org/sid/python3-rq) (on Debian) and [Record Query](https://github.com/dflemstr/rq) (on NixOS).

`hr` is the name of several horizontal ruler programs ([1](https://github.com/LuRsT/hr), [2](https://github.com/djmattyg007/hr), [3](https://github.com/etiennebatise/hr-rs)). One of them is on crates.io, and multiple are in the AUR.

I can't find anything called `xh`, except an empty NPM package. So that would be suitable.

**Comment by ducaale** [comment]
That settles it then. Moving to the new name would require the following steps (correct me if I am missing anything): 
- Replace any `ht` references with `xh` (including the demo).
- Temporarily remove the installation section from `README.md`.
- Make a new minor release (should be ok since we haven't hit v1.0 yet).
- Upload the renamed binary to crates.io

`ht` is currently being published in the following places:
- **homebrew**: contributed by @dtrodrigues
- **Arch**: contributed by @orhun
- **nixpkgs**: contributed by @payasrelekar
- **scoop** (pending): contributed by @myty

After some googling, I found docs on how to [rename a package in homebrew](https://docs.brew.sh/Rename-A-Formula). However, I am not sure how it would be done for others.

**Comment by blyxxyz** [comment]
> Make a new minor release (should be ok since we haven't hit v1.0 yet).

Do you mean a final release on crates.io pointing people towards the new name? How heavy-handed would it be?

**Comment by ducaale** [comment]
No, I meant the new `xh` release to be v0.7.0.

>Do you mean a final release on crates.io pointing people towards the new name? How heavy-handed would it be?

I think a simple message like this would suffice:

```
ht has moved to [xh](https://crates.io/crates/ht). For more context behind the change, see 
[#1](https://github.com/ducaale/ht/issues/1)
```

**Comment by ducaale** [comment]
`ht` has now been successfully renamed to `xh`. Thanks to @mehcode for suggesting the new name, and thanks to everyone who raised the `tex-live` name collision issue.

**Comment by orhun** [comment]
I renamed `ht` to `xh`: https://archlinux.org/packages/community/x86_64/xh/
You can add the same (`s/ht/xh/`) Arch Linux instructions back (#43) (if you like) or I can submit a PR again.

**Comment by ducaale** [comment]
Thanks, @orhun. I've added it back to `README.md`.
