### ISSUE TITLE
Generated numbers for names are added after the file extension

### ISSUE THREAD

**Issue by ducaale** [ducaale/xh#104]
#### Reproduction steps:
```
$ xh httpbin.org/json -d
$ xh httpbin.org/json -d
```

#### Expected:
```
$ ls
json.json
json-1.json
```

#### Actual:
```
$ ls
json.json
json.json-1
```

**Comment by blyxxyz** [comment]
HTTPie also makes it `json.json-1`, and wget makes it `json.json.1`. So I'm not sure we should change it.

**Comment by ducaale** [comment]
Makes sense, I will close this issue then 👍
