### ISSUE TITLE
Option to force TLS version

### ISSUE THREAD

**Issue by sorairolake** [ducaale/xh#120]
HTTPie has an option to force TLS version. I think it would be useful if xh also has this.

see also: [HTTPie documentation](https://httpie.io/docs#ssl-version)

**Comment by blyxxyz** [comment]
This is slightly tricky, but I think it can be done by calling [`use_preconfigured_tls`](https://docs.rs/reqwest/0.11.3/reqwest/blocking/struct.ClientBuilder.html#method.use_preconfigured_tls) with a [`rustls::ClientConfig`](https://docs.rs/rustls/0.19.1/rustls/struct.ClientConfig.html) or a [`native_tls::TlsConnector`](https://docs.rs/native-tls/0.2.7/native_tls/struct.TlsConnector.html).

If you don't keep your rustls and and native_tls versions in sync with the ones reqwest uses it silently ignores your config at runtime. So an update to reqwest could break xh without us noticing. I don't like that.

Maybe we could add this as a proper feature to reqwest first.

**Comment by blyxxyz** [comment]
It's a known issue, listed in the docs and unavoidable with the way the signatures are structured. I'd rather have it as a proper reqwest feature, if possible.

### reqwest

I looked into implementing it at the time. native-tls lets you set a [minimum version](https://docs.rs/native-tls/0.2.7/native_tls/struct.TlsConnectorBuilder.html#method.min_protocol_version) and [maximum version](https://docs.rs/native-tls/0.2.7/native_tls/struct.TlsConnectorBuilder.html#method.max_protocol_version) while rustls lets you set [the exact supported versions](https://docs.rs/rustls/0.19.1/rustls/struct.ClientConfig.html#structfield.versions). [rustls](https://docs.rs/rustls/0.19.1/rustls/internal/msgs/enums/enum.ProtocolVersion.html) supports more versions than [native-tls](https://docs.rs/native-tls/0.2.7/native_tls/enum.Protocol.html).

A lowest common denominator API might let you set an (optional) minimum and (optional) maximum using an enum provided by reqwest, with some logic to translate that into rustls terms. You'd have to take care to make it future-proof for when a new version comes out, but I think it's possible.

### HTTPie

HTTPie supports `--ssl ssl2.3`. That's bogus, it maps to [`PROTOCOL_SSLv23`](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_SSLv23), which is an alias for `PROTOCOL_TLS`, which "selects the highest protocol version that both the client and server support", regardless of whether that's SSL or TLS. There is no SSL v2.3. [The docs](https://httpie.io/docs#ssl-version) are basically accurate, so this isn't a big deal, but we might want to only have it as a hidden alias or something.

(https://badssl.com was helpful for testing.)

### OpenSSL

Python's docs tell me that "OpenSSL has deprecated all version specific protocols". That would explain why `native_tls::Protocol` doesn't have a `Tlsv13` variant, and why Python's ssl module has no `PROTOCOL_TLSv1_3`. On the other hand there is [`SSLContext.maximum_version`](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.maximum_version) and [`TLSVersion.TLSv1_3`](https://docs.python.org/3/library/ssl.html#ssl.TLSVersion.TLSv1_3), but only as of version 1.1.0g (2 nov 2017, too recent to rely on).

This is further backed up by the `openssl` crate, which has `min_proto_version` supported as of [OpenSSL 1.1.0g](https://docs.rs/openssl/0.10.34/src/openssl/ssl/mod.rs.html#1232) and `SslVersion::TLS1_3` as of [OpenSSL 1.1.0](https://docs.rs/openssl/0.10.34/src/openssl/ssl/mod.rs.html#618).

I don't know if it's possible to force TLS v1.3 between 1.1.0 and 1.1.0g, where I think there's no `min_proto_version` but there is `TLS1_3`.

To support `--ssl tls1.3` we'd probably have to improve the native-tls crate to do tricky feature detection. (But that's assuming only OpenSSL is the problem and there's nothing going on with schannel (Windows) or security-framework (macOS), and assuming native-tls doesn't mind the complexity. I haven't checked their issue tracker, maybe there's something in there?)

### HTTPie (again)

HTTPie has the same conundrum with `--ssl tls1.3`: httpie/httpie#722

I may try to fix it there first and see if the experience helps here.

**Comment by blyxxyz** [comment]
I'm just going to implement this for reqwest without supporting 1.3 for native-tls.

That'll also let us raise the minimum default TLS version to 1.2. Right now `http https://tls-v1-1.badssl.com:1011/` fails and `curl https://tls-v1-1.badssl.com:1011/` fails but `xh --native-tls https://tls-v1-1.badssl.com:1011/` succeeds. That seems bad.

(rustls only supports 1.2 and 1.3 to begin with.)

**Comment by blyxxyz** [comment]
> That'll also let us raise the minimum default TLS version to 1.2.

After some further investigation I'm deciding against this (at least for now). HTTPie and curl fail because my build of OpenSSL has a minimum of 1.2, but I think that's hardening by Debian. curl's fallback default minimum version is 1.0, same as the non-fallback default minimum of native-tls, and apparently Microsoft's browsers are also sticking to a minimum of 1.0 until early 2022.

We can defer to native-tls and let them decide.

**Comment by ducaale** [comment]
As of v0.14.0, xh has support for setting the TLS version.

**Comment by sorairolake** [comment]
Thank you @blyxxyz
