### ISSUE TITLE
[Feature] One-line binary install improvement

### ISSUE THREAD

**Issue by thernstig** [ducaale/xh#121]
I have a plethora of great statically linked binary installs in Linux (Ubuntu). These include `ripgrep`, `exa`, `bat`, `fd` etc. None shines as well as `chezmoi` when it comes to the one-line installer.

I recommend to implement a one-line binary installer to follow that of `chezmoi`. See this documentation: https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md#one-line-binary-install

In effect, what it does, is to download the latest statically linked binary for your operating system and architecture into `./bin`
This means I can put myself in whatever dir I want and just call the installer and it will be installed into the bin path of my choosing. Be that `~/bin` or `.local/bin` or whatever I prefer.

**Comment by thernstig** [comment]
Also does xh currently even support `linux-amd64`? Couldn't find a build for it at https://github.com/ducaale/xh/releases

**Comment by blyxxyz** [comment]
chezmoi's [installer](https://github.com/twpayne/chezmoi/blob/master/assets/scripts/install.sh) looks interesting. Installing into `./bin/` by default isn't what I would expect though.

> Also does xh currently even support `linux-amd64`?

Yes, but it's called `x86_64-unknown-linux-musl`.

We already have an issue for this at #117, so maybe we should continue there?

**Comment by ducaale** [comment]
Nah, I will close #117 instead since this one has more information.

By the way, I like how `chezmoi`'s installation instruction is organized on a table. This is something that [zoxide](https://github.com/ajeetdsouza/zoxide#getting-started) does as well.

**Comment by thernstig** [comment]
Maybe the `./bin` could be a default but that you also can add a parameter to install into any path specified?

**Comment by ducaale** [comment]
@thernstig would it be problematic if we only support installing the binary to `/usr/local/bin/`?

**Comment by thernstig** [comment]
@ducaale Yes because it is shared between users, whereas most user prefer to install into a local bin directory.

**Comment by ducaale** [comment]
I think there are some distros where `$HOME/bin` is not in `$PATH` by default. So in the interest of achieving user convenience, I think it would be best to default to `/usr/local/bin` while supporting customizing the install location via an env variable.

```sh
# install to /usr/local/bin
curl -sfL https://raw.githubusercontent.com/ducaale/xh/master/install.sh | sh

# install to custom directory e.g $HOME/bin
curl -sfL https://raw.githubusercontent.com/ducaale/xh/master/install.sh | bindir="$HOME/bin" sh
```

**Comment by ducaale** [comment]
xh v0.10.0 has been released which comes with an install script 🎉

```
curl -sfL https://raw.githubusercontent.com/ducaale/xh/master/install.sh | sh
```

**Comment by thernstig** [comment]
@ducaale I am in the midst of creating a generic one line binary installer like this that works for any project (xh, fzf, bat etc.). Just for fun. But glad this landed!
