### ISSUE TITLE
[Example] File upload

### ISSUE THREAD

**Issue by sergeevabc** [ducaale/xh#127]
Dear @ducaale, could you be so kind to tell what is the `xh` equivalent of the following `curl` command to upload a file?

``` console
$ curl.exe -F filedata=@helloworld.txt https://transfer.sh/
```

**Comment by blyxxyz** [comment]
This should do the trick:
```
xh.exe -f https://transfer.sh filedata@helloworld.txt
```
I would recommend [curl2httpie](https://curl2httpie.online/) but it seems the website is offline.

I think [HTTPie's docs](https://httpie.io/docs#file-upload-forms) are the best reference for now.

**Comment by sergeevabc** [comment]
It does the trick indeed, but one crucial response header is missing in the output as follows
``` console
$ curlie.exe --upload-file helloworld.txt https://transfer.sh/   
https://transfer.sh/JEpCc/helloworld.txt
HTTP/2 200                                   
content-type: text/plain                                                             
server: Transfer.sh HTTP Server 1.0                                                  
x-made-with: <3 by DutchCoders                                                       
x-served-by: Proudly served by DutchCoders                                           
x-url-delete: https://transfer.sh/JEpCc/helloworld.txt/tpsW6OYTEW                    <------------- !!!
...

$  xh.exe https://transfer.sh -f filedata@helloworld.txt
HTTP/2.0 200 OK                             
...
x-made-with: <3 by DutchCoders              
x-served-by: Proudly served by DutchCoders  
https://transfer.sh/90SOG/helloworld.txt    
```

**Comment by blyxxyz** [comment]
Hmm, that's different from the `curl` command from before. It executes a PUT request for `https://transfer.sh/helloworld.txt`. For some reason transfer.sh only sends a X-Url-Delete header if you do it that way.

This works:
```
xh put https://transfer.sh/helloworld.txt < helloworld.txt
```
(but I'm not sure if it translates to Windows properly)

This works in HTTPie:
```
http put https://transfer.sh/helloworld.txt @helloworld.txt
```
I intend to add support for that to xh as well.

**Comment by sergeevabc** [comment]
@blyxxyz, I deleted HTTPie, because of its bloated 11+ MiB size, not to mention it takes annoying >1 sec to launch on my end.
That’s why am looking forward to follow, as the frontpage of XH says, a more “friendly and fast tool for sending HTTP requests”.

**Comment by ducaale** [comment]
I think something like this works in PowerShell for Windows (might not work for binary files)
```
cat helloworld.txt | xh -v put https://transfer.sh/helloworld.txt
```

**Comment by sergeevabc** [comment]
@ducaale, I have `cat` as a part of MSYS2 package, but the way you offered is not intuitive because my local filename is used twice, especially that addition to the remote hostname. The simple train of thought is [util] [action] [local] [remote] or [remote] [local], so it is expected to have something as follows `xh put myLocalFile thatRemoteHost` or `upload` instead of `put` as a special case.

**Comment by blyxxyz** [comment]
Here's the transfer.sh issue for not getting a deletion URL on a POST request: dutchcoders/transfer.sh#237

-----

> my local filename is used twice

That's unfortunate, yeah.

If you don't care whether transfer.sh knows your local filename then you can use something short, e.g. `xh put https://transfer.sh/x`. But leaving it off entirely doesn't work.

Personally I like to make simple scripts/aliases for these things. I don't know how it works on Windows, but on Linux I'd define `alias transfer='curl -i https://transfer.sh --upload-file'`. Then I can just run `transfer helloworld.txt`, which is as simple as it gets.

I don't think this would be a good feature for xh. It's not in HTTPie either, so apparently they didn't find a need. curl is extremely versatile, it's ok if it's better at some things.

An `upload` special method would also work radically different from the normal HTTP methods. It'd basically be a subcommand, and we don't have real subcommands. So it would make xh more complicated.
