### ISSUE TITLE
Automate the generation of negation flags

### ISSUE THREAD

**Issue by ducaale** [ducaale/xh#142]
Currently, we have a `NEGATION_FLAGS` list that needs to be manually updated whenever we add a new flag. A quick search reveals that it's possible to [extract field names from a struct](https://stackoverflow.com/questions/29986057/is-there-a-way-to-get-the-field-names-of-a-struct-in-a-macro/29986760#29986760) using a macro rule. I think this can be temporarily used to generate the said list until we can come up with a proper derive macro solution.

**Comment by ducaale** [comment]
Actually, I think this gets tricky when field names are in snake case but the negated flags need to be in kebab case

```rust
macro_rules! with_negation_flags {
    (
        $(#[$($struct_meta:meta),+])* $struct_vis:vis struct $struct_name:ident {
            $(
                $(#[$($field_meta:meta),+])*
                $field_vis:vis $field_name:ident: $field_type:ty
            ),*
            $(,)?
        }
    ) => {
        $(#[$($struct_meta),+])* $struct_vis struct $struct_name {
            $(
                $(#[$($field_meta),+])*
                $field_vis $field_name: $field_type
            ),*
        }

        impl $struct_name {
            #[allow(dead_code)]
            fn negated_flags() -> Vec<&'static str> {
                // can we construct kebab cased string with static lifetime?
                vec![$(concat!("--no-", stringify!($field_name))),*]
            }
        }
    }
}

with_negated_flags! {
    /// xh is a friendly and fast tool for sending HTTP requests.
    ///
    /// It reimplements as much as possible of HTTPie's excellent design.
    #[derive(StructOpt, Debug)]
    #[structopt(name = "xh")]
    struct Cli {
        /// Create, or reuse and update a session.
        #[structopt(long, value_name = "FILE")]
        session_read_only: Option<String>
    }
}
```

We could explicitly annotate each field with clap's name attribute or come up with a less hacky solution via a proc macro.

**Comment by blyxxyz** [comment]
I think I like a macro less than a simple list with no hidden parts. There's a little manual work, but it adds up to less work than the work needed to automate it, and it's easier to understand.

Implementing clap-rs/clap#815 might be a better solution. It could be less fragile and benefit more people.

**Comment by ducaale** [comment]
I agree that implementing https://github.com/clap-rs/clap/issues/815 would be the best solution. However, it doesn't seem to be a trivial thing. See https://github.com/clap-rs/clap/issues/1041#issuecomment-343763399 and https://github.com/clap-rs/clap/pull/1728.

Lifetimes are less of a problem once macros are in use so I wonder if this could be supported in structopt? Although I am not sure what is their policy regarding compatibility with clap-rs.

**Comment by ducaale** [comment]
This has been addressed in https://github.com/ducaale/xh/pull/234
