### ISSUE TITLE
Make `--check-status` default

### ISSUE THREAD

**Issue by Livven** [ducaale/xh#144]
IMO this is a major issue for both curl and httpie that should be fixed in a Rust rewrite. Specifically:

- For interactive use, exit codes don't matter that much. Personally, I use a prompt that indicates the last exit code, but many people don't. In any case, switching to error codes shouldn't cause any issues here.
- For scripting, the current behavior is an unsafe default. Sure, there are valid uses of accepting non-200 statuses, but that should be opt-in. One of the selling points of Rust rewrites is using sensible defaults, such as ripgrep or fd excluding hidden and gitignored files. There are already way too many shell scripts out there not using `curl --fail` or `http --check-status` (or even `set -e`).

Thoughts?

**Comment by blyxxyz** [comment]
I think that makes sense. Do you know if there's previous discussion of this default for HTTPie or other tools?

If we do this we should perhaps also have a strict compatibility mode to change the default back, like some GNU tools have for POSIX.

**Comment by Livven** [comment]
Only found https://github.com/httpie/httpie/issues/611 but that is not about changing the default. In general, I guess there is little hope of such a change in existing tools as it would be breaking a lot of existing users. This being a newer, pre-1.0, Rust project I had more hope :)

There definitely should be a `--no-check-status` or similar flag as well. Apart from that, not sure whether full httpie compatibility is a priority for this project. I can see arguments for both sides; on the one hand, httpie itself is already quite modern, so there is less (but not zero) pressure to diverge, but conversely, it's not a "standard" Unix tool anyway, so why even bother.

**Comment by ducaale** [comment]
>There definitely should be a --no-check-status or similar flag as well.

Similar to HTTPie, every flag can be prefixed with `--no-` to unset it.

>Apart from that, not sure whether full httpie compatibility is a priority for this project.

It is hard to say. Breaking compatibility with HTTPie means we can supporting new features like [nested JSON syntax](https://github.com/ducaale/xh/issues/3) without too much headache. However, it would also mean we are no longer a drop-in replacement for HTTPie and any hopes of this project being [integrated into HTTPie](https://crates.io/crates/httpie) might fade away.

But @blyxxyz's idea of a compatibility mode seems the most sensible approach. Maybe we could use the binary name to achieve that so if it is either `http` or `https`, we turn on strict compatibility mode?

**Comment by ducaale** [comment]
`--check-status` is now enabled by default in v0.11.0. We also support opting out of this change by enabling xh's [strict compatibility mode](https://github.com/ducaale/xh#strict-compatibility-mode)
>If xh is invoked as http or https (by renaming the binary), or if the XH_HTTPIE_COMPAT_MODE environment variable is set, it will run in HTTPie compatibility mode. The only current difference is that --check-status is not enabled by default.
