### ISSUE TITLE
Fixes for clap v3

### ISSUE THREAD

**Issue by blyxxyz** [ducaale/xh#152]
There are a few bugs and workarounds that we can get rid of after clap 3 releases.

- [ ] [Manual `NO_COLOR` check](https://github.com/ducaale/xh/blob/95d6fc7d5920ad4b56ff06610cd2ee69bb37233d/src/cli.rs#L439): clap 3 switched to `termcolor` so this would no longer be necessary.
- [ ] [Incorrectly colored error message](https://github.com/ducaale/xh/pull/151#issuecomment-855221819): Likely fixed by `termcolor`, not easily fixable yet because clap's `ColorWhen` type isn't exported.
- [ ] [fish shell completions](https://github.com/ducaale/xh/blob/95d6fc7d5920ad4b56ff06610cd2ee69bb37233d/src/cli.rs#L499): Fix merged upstream.
- [ ] [triple `{n}`](https://github.com/ducaale/xh/blob/ab138a8dcc60d9a58f00575a839f83e498f4ec58/src/cli.rs#L24): No longer needed.

There are probably others I can't remember at the moment.

**Comment by ducaale** [comment]
We can also get rid of the [triple `{n}`](https://github.com/ducaale/xh/blob/ab138a8dcc60d9a58f00575a839f83e498f4ec58/src/cli.rs#L61) we have after each long help text

**Comment by blyxxyz** [comment]
A [release candidate](https://docs.rs/clap/3.0.0-rc.0/clap/index.html) is out.

Its MSRV is 1.54, so we'll have to bump our own to use it.

**Comment by ducaale** [comment]
Clap v3.0 has now been officially released 🎉.

See https://epage.github.io/blog/2021/12/clap3/.

**Comment by ducaale** [comment]
I will close this issue since these fixes are now in `develop`.
