### ISSUE TITLE
Option to set filename for multipart uploads

### ISSUE THREAD

**Issue by abonander** [ducaale/xh#162]
See header "Pinning a Directory Example": https://pinata.cloud/documentation#PinFileToIPFS

Essentially, I need to be able to set the filename of a multipart form part to be, e.g. `./foo/bar.jpg` and not just `bar.jpg` if I upload `foo/bar.jpg`.

Looks like the request item parsing already supports overriding the `Content-Type` of the file part with `;type=`: https://github.com/ducaale/xh/blob/master/src/request_items.rs#L105

So maybe `file@./foo/bar.jpg;filename=./foo/bar.jpg`? It's a bit verbose but I can work with it.

**Comment by blyxxyz** [comment]
curl supports exactly that syntax for exactly that use case, so I think that makes sense. (It additionally has `;headers=` but let's ignore that for now.)

I can't find any discussion about it for HTTPie.

**Comment by abonander** [comment]
Man, cURL's manpage is so dense I couldn't actually find that even though I was just looking at the `--form` option. I actually just ended up banging out a binary in my project to do it reqwest :laughing:.

**Comment by ducaale** [comment]
xh v0.11.0 has been released which supports setting the filename for multipart uploads 🎉

```
$ xh httpbin.org/post --form --offline "file@sample.txt;filename=./foo/bar.jpg"
POST /post HTTP/1.1
accept: */*
accept-encoding: gzip, deflate, br
connection: keep-alive
content-type: multipart/form-data; boundary=4d5b5a90928f0b1c-40b0841c81cbfc2b-91a21457f0ccb322-50b149ba0441061c
host: httpbin.org
user-agent: xh/0.11.0

--4d5b5a90928f0b1c-40b0841c81cbfc2b-91a21457f0ccb322-50b149ba0441061c
Content-Disposition: form-data; name="file"; filename="./foo/bar.jpg"

hello world

--4d5b5a90928f0b1c-40b0841c81cbfc2b-91a21457f0ccb322-50b149ba0441061c--
```
