### ISSUE TITLE
dns error: failed to lookup address information: Temporary failure in name resolution

### ISSUE THREAD

**Issue by horseinthesky** [ducaale/xh#163]
Hello.

Trying to move `httpie` example:
```
http GET <url> param1=value1 param2=value2 'Authorization: Bearer <supersecrettoken>' --verify no
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 122
Content-Type: application/json
Date: Wed, 14 Jul 2021 19:01:23 GMT
Server: nginx/1.12.2
Strict-Transport-Security: max-age=31536000;

{
    "code": 200,
    "result": {
        <some_data>
    },
    "status": "ok"
}
```

to `xh`:
```
xh --bearer <supersecrettoken> --verify no <url> param1=value1 param2=value2
Error: error sending request for url (<url>): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    1: dns error: failed to lookup address information: Temporary failure in name resolution
    2: failed to lookup address information: Temporary failure in name resolution
 ```
    
 What am I doing wrong?

**Comment by blyxxyz** [comment]
I don't see anything obviously wrong. Maybe it's a temporary issue that'll go away if you retry.

Could you tell us the URL, or at least the hostname?

**Comment by horseinthesky** [comment]
@blyxxyz I've tried several times. It doesn't seem to be anything wrong with DNS itself.

`<url>` is my internal API endpoint `https://<group>.<department>.<company>.net/api/<endpoint_name>`

**Comment by blyxxyz** [comment]
Without knowing an exact hostname (`<group>.<department>.<company>.net`) so I can try for myself there's not much I can do, sorry. If that's too revealing then maybe you could insert another group and department that works with HTTPie and not xh? Or perhaps you can email me?

If you'd like to try debugging this for yourself then you could try writing a small program with [reqwest](https://lib.rs/crates/reqwest) to reproduce it, and use [pretty_env_logger](https://lib.rs/crates/pretty_env_logger) to look at the logs.

**Comment by horseinthesky** [comment]
Since it is internal you cannot try it anyway. I would gladly provide public if I had one. Sorry.

Not known Rust at all is there anything I can do to troubleshoot it without learning how to use `reqwest` and `pretty_env_logger`?

**Comment by blyxxyz** [comment]
We should probably integrate it into xh some time so you can just enable logging by adding a flag.

I wrote a small [example](https://github.com/blyxxyz/simreq) with instructions, but it doesn't seem to log much about DNS, so I'm not sure if it'll be helpful.

-----

One other thing I can think of is to look at the raw DNS traffic. You can install tcpdump and run `sudo tcpdump udp port 53 -vv`.

I don't know enough about DNS to understand everything, but if I request `http://notarealdomainatall` I see `[udp sum ok] 4380 NXDomain q: A? notarealdomainatall.` among the messages. And if I request `http://example.org` I see `[udp sum ok] 19179 q: A? example.org. 1/0/0 example.org. A 93.184.216.34`. There's a good chance you'll get something else instead of either of those, but seeing what it is and seeing if it's different from HTTPie in some way would be informative.

**Comment by horseinthesky** [comment]
This `simreq` shows 403 (which is correct answer without token provided)
```
 TRACE reqwest::blocking::wait > (ThreadId(1)) park without timeout
 TRACE reqwest::blocking::client > (ThreadId(2)) start runtime::block_on
 TRACE reqwest::blocking::wait   > wait at most 30s
 TRACE reqwest::blocking::wait   > (ThreadId(1)) park timeout 29.9999753s
 DEBUG reqwest::connect          > starting new connection: https://<group>.<department>.net/
 TRACE mio::poll                 > registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
 TRACE want                      > signal: Want
 TRACE want                      > signal found waiting giver, notifying
 TRACE want                      > poll_want: taker wants!
 TRACE want                      > signal: Want
 TRACE want                      > signal: Want
 DEBUG reqwest::async_impl::client > response '403 Forbidden' for https://<group>.<department>.<company>.net/api/<endpoint_name>
Response {
    url: Url {
        scheme: "https",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Domain(
                "<group>.<department>.<company>.net",
            ),
        ),
        port: None,
        path: "/api/<endpoint_name>",
        query: None,
        fragment: None,
    },
    status: 403,
    headers: {
        "server": "nginx/1.12.2",
        "date": "Wed, 14 Jul 2021 20:42:57 GMT",
        "content-type": "application/json",
        "content-length": "30",
        "connection": "keep-alive",
        "strict-transport-security": "max-age=31536000;",
    },
}
 TRACE reqwest::blocking::client   > closing runtime thread (ThreadId(2))
 TRACE want                        > signal: Want
 TRACE reqwest::blocking::client   > signaled close for runtime thread (ThreadId(2))
 TRACE reqwest::blocking::client   > (ThreadId(2)) Receiver is shutdown
 TRACE reqwest::blocking::client   > (ThreadId(2)) end runtime::block_on
 TRACE mio::poll                   > deregistering event source from poller
 TRACE want                        > signal: Closed
 TRACE reqwest::blocking::client   > (ThreadId(2)) finished
 TRACE reqwest::blocking::client   > closed runtime thread (ThreadId(2))
 ```
 
 I forgot to mention it is IPv6 only and if this can be an issue...and then it started working >.<
![image](https://user-images.githubusercontent.com/19948672/125691529-6e028a81-9767-466e-ae4f-9da272b86c99.png)
Almost twice as fast as `httpie` on my slow machine. Amazing!

Sorry for bothering.

**Comment by blyxxyz** [comment]
No problem! Maybe it was just a random blip, but I wouldn't be surprised if there is some real issue at the root. We've run into such cases before, like #135.

**Comment by horseinthesky** [comment]
Thank you. I will try to find as many details as possible from a network perspective in case this happens again.
