### ISSUE TITLE
xh lowercases all headers

### ISSUE THREAD

**Issue by CosmicToast** [ducaale/xh#166]
## What I expect
Xh copies case of user-specified headers.

## What actually happens
Xh treats all headers as case-insensitive and lowercases them.

## Why is this a problem?
1. It's a difference from httpie.
2. It has a negative net effect when interacting with non-compliant servers.

To explain 2...

Some services treat headers as case-sensitive (e.g with `X-*` headers, especially for auth).
The HTTP specification does specify that headers are case-insensitive, however, consider the following matrix.
If headers are treated as case insensitive, this will break servers that (incorrectly) treat them as case-sensitive, while not having a negative effect on compliant servers.
If headers are treated as case sensitive, this will work with the non-compliant servers, while not having a negative effect on compliant servers.

It would also be ok to auto-capitalize headers (e.g `foO-baR-baZ` could become `Foo-Bar-Baz`), since that's what standard industry practice anyway, but this is not what HTTPie does.

## How to test compliance
`xh --print=H localhost My-OdDlY-Capitalized-Header:Here`
compare to
`http --print=H localhost My-OdDlY-Capitalized-Header:Here`

**Comment by blyxxyz** [comment]
The libraries we use limit us here, unfortunately. They don't support case sensitivity for header names.

There's an [option](https://docs.rs/reqwest/0.11.4/reqwest/struct.ClientBuilder.html#method.http1_title_case_headers) to send all headers in title-case (i.e. auto-capitalize them). Maybe it would be better to enable that.

We'd have to manually capitalize the headers for display (by copying [how `hyper` does it](https://github.com/hyperium/hyper/blob/54b57c4797e1210924d901a665f9d17ae7dd9956/src/proto/h1/role.rs#L1315)).

We also have to think about the response headers. Displaying them in lowercase hints that they've been normalized, displaying them in title case doesn't. (And displaying them in title case if the response is HTTP/2 is technically flat out incorrect, HTTP/2 requires headers to be lowercase.)

Did you run into this in the wild?

**Comment by CosmicToast** [comment]
Yes, I ran into this with [Zilore's](https://zilore.com/) API.
HTTPie and HTTPie-Go both managed just fine (the latter sends headers in title-case, the former preserves case), but on xh I was getting 403 forbidden.

**Comment by ducaale** [comment]
>There's an option to send all headers in title-case (i.e. auto-capitalize them). Maybe it would be better to enable that.

Since this option doesn't seem to work with HTTP/2 enabled servers, it might be better to have this as a flag rather being enabled by default.

### HTTP/1.1
<img width="806" alt="Screenshot 2021-08-03 234621" src="https://user-images.githubusercontent.com/16341131/128084018-c77e0fa2-c5eb-44f8-a7ef-31eb61ffe27a.png">

### HTTP/2
<img width="806" alt="Screenshot 2021-08-03 234550" src="https://user-images.githubusercontent.com/16341131/128084043-72bf8d89-fe69-4c32-8404-5a55a2e643cd.png">

**Comment by blyxxyz** [comment]
That's expected behavior, HTTP/2 simply requires all header names to be lowercase.

If we know that a request or response is HTTP/2 then we can still print the headers as lowercase.

I can't think of a situation where someone would require lowercase headers for HTTP/1.1 so I don't think there's a reason to hide it behind a flag.

**Comment by CosmicToast** [comment]
Just in case this isn't a known fact - httpbin.org (and all hosted versions of it, such as pie.dev) title-case the headers they receive.
Consider the following:
`curl -H 'Foo-Bar: Baz' https://pie.dev/headers`
vs
`curl -H 'foo-bar: baz' https://pie.dev/headers`

In both cases, pie.dev will report "Foo-Bar" as the header, so it's not a reliable testing mechanism (for this specific use-case).
It wasn't explicitly used here, but it may be worth mentioning (since I tested with that first and it took me a little bit to figure out what was going on).
This is why my test case uses `--print=H`.

**Comment by blyxxyz** [comment]
Note that even `--print=H` doesn't necessarily reflect what's going over the wire. I tend to run a "server" with `while nc -l -p 8080; do :; done` to see exactly what's coming in. (You don't get a response that way, so it's a bit limited.)

**Comment by ducaale** [comment]
xh now sends header names as title-case as of v0.12.0 (except for HTTP/2 connections)

**Comment by rburgst** [comment]
I fear that automatically title casing headers is not a good idea and is certainly unexpected (at least for me).
Note that `httpie` will not auto title case headers if you provide them in all lowercase.

**Comment by blyxxyz** [comment]
> I fear that automatically title casing headers is not a good idea and is certainly unexpected (at least for me). Note that `httpie` will not auto title case headers if you provide them in all lowercase.

It's a limitation of the libraries we use. It's not really something we like, the README lists it as a disadvantage compared to HTTPie.

We can send all headers lowercase, or we can send all headers title-cased, with no other options. Title case seems better than lowercase.
