### ISSUE TITLE
Support silencing warnings via double `-q` flag

### ISSUE THREAD

**Issue by ducaale** [ducaale/xh#179]
See https://github.com/httpie/httpie/issues/1100 and https://github.com/httpie/httpie/pull/1175

**Comment by Abdiramen** [comment]
I'm considering implementing this feature but it seems that `xh` already silences warnings.

```shell
   ~ ─────────────────────────────────────────────────────────────────────────────── 19:22:57 
❯ http --check-status --quiet pie.dev/status/500

http: warning: HTTP 500 Internal Server Error

   ~ ─────────────────────────────────────────────────────────────────────────────── 19:23:09 
❯ xh --check-status --quiet pie.dev/status/500
   ~ ─────────────────────────────────────────────────────────────────────────────── 19:23:18 
❯
```
Should this be changed along with the addition of `-qq`?

**Comment by ducaale** [comment]
>Should this be changed along with the addition of -qq?

Yes, please. Unlike HTTPie, we aren't currently outputting HTTP warnings if the `--quite` or `--output` flag is being used.

#### xh
```
$ xh --check-status --quiet pie.dev/status/500
$ xh --check-status --output /dev/null pie.dev/status/500
$ xh --check-status pie.dev/status/500 > /dev/null
xh: warning: HTTP 500 Internal Server Error
```
#### HTTPie
```
$ http --check-status --quiet pie.dev/status/500

http: warning: HTTP 500 Internal Server Error

$ http --check-status --output /dev/null pie.dev/status/500

http: warning: HTTP 500 Internal Server Error

$ http --check-status pie.dev/status/500 > /dev/null

http: warning: HTTP 500 Internal Server Error

```

This can be fixed by:
1. Modifying this [line](https://github.com/ducaale/xh/blob/806af98ad3eadb71f7433848304166e315948bea/src/main.rs#L435) to take `args.quite` into account.
2. Checking if we're not [outputting](https://github.com/ducaale/xh/blob/806af98ad3eadb71f7433848304166e315948bea/src/main.rs#L386) into the terminal instead of checking if we have a redirected output.

**Comment by farmeroy** [comment]
Is this issue still open?
