### ISSUE TITLE
xh lowercases path to CA bundle

### ISSUE THREAD

**Issue by m2608** [ducaale/xh#180]
Eg. I put CA bundle in folder "Certs". But xh looks for bundle in "certs" folder instead. As a result, it becomes impossible to use path which contain capitals letters. You could also create "certs" folder, it this case xh will use wrong CA bundle.

```
~# xh -h --proxy https:http://localhost:8080 --verify Certs/mitmproxy-ca-cert.pem https://google.com
xh: error: Failed to open the custom CA bundle: certs/mitmproxy-ca-cert.pem

Caused by:
    No such file or directory (os error 2)
```

**Comment by ducaale** [comment]
A fix for this has been included in the newly released xh v0.14.0 👍
