### ISSUE TITLE
Consider replacing httpmock with hyper+helpers

### ISSUE THREAD

**Issue by ducaale** [ducaale/xh#186]
### My reasons against Httpmock
1. It has a dependency on `curl+openssl` which can be problematic when running tests in CI.
2. It is not possible to have a custom logic that returns a [different response depending on the request](https://github.com/alexliesenfeld/httpmock/issues/49).
3. `Httpmock::When` [cannot be currently extended]( https://github.com/alexliesenfeld/httpmock/issues/44#issuecomment-840797442). This limitation can sometimes force us to either duplicate code or [use macros](https://github.com/ducaale/xh/pull/125#discussion_r658814597).

On the other hand, `hyper`+[helpers](https://github.com/seanmonstar/reqwest/tree/master/tests/support) can do everything `httpmock` does without the mentioned limitations. The only problem I can think of is that hyper can be a bit verbose but that verbosity can be easily abstracted away (I think).

### A typical Httpmock test
```rust
#[test]
fn basic_json_post() {
    let server = MockServer::start();
    let mock = server.mock(|when, then| {
        when.method(POST)
            .header("Content-Type", "application/json")
            .json_body(json!({"name": "ali"}));
        then.header("Content-Type", "application/json")
            .json_body(json!({"got": "name", "status": "ok"}));
    });

    get_command()
        .arg("--print=b")
        .arg("--pretty=format")
        .arg("post")
        .arg(server.base_url())
        .arg("name=ali")
        .assert();

    mock.assert();
}
```

### The same test but in hyper
```rust
// Inspired by reqwest's tests. See https://github.com/seanmonstar/reqwest/tree/master/tests
#[tokio::test]
async fn basic_json_post() {
    let server = server::http(move |req| async move {
        assert_eq!(req.method(), "POST");
        assert_eq!(req.headers()["Content-Type"], "application/json");
        let mut full: Vec<u8> = Vec::new();
        while let Some(item) = req.body_mut().next().await {
            full.extend(&*item.unwrap());
        }
        assert_eq!(full, b"{\"name\": \"ali\"}");

        http::Response::builder()
            .header(http::header::CONTENT_TYPE, "application/json")
            .body("{\"got\": \"name\", \"status\": \"ok\"}".into())
            .unwrap()   
    });

    get_command()
        .arg("--print=b")
        .arg("--pretty=format")
        .arg("post")
        .arg(server.addr())
        .arg("name=ali")
        .assert();
}
```

**Comment by blyxxyz** [comment]
I think that's a good idea. FreeBSD also [patches](https://cgit.freebsd.org/ports/tree/www/xh/files/patch-Cargo.toml) us just to deal with curl. The code looks cleaner than I expected, seems very manageable.

Is this really the easiest way to read the request body, though?
```rust
        let mut full: Vec<u8> = Vec::new();
        while let Some(item) = req.body_mut().next().await {
            full.extend(&*item.unwrap());
        }
```
We can always just wrap a helper function around it, but it surprised me.

**Comment by ducaale** [comment]
As you suspected, there is an easier way to [read the request body](https://stackoverflow.com/a/59428403/5915221).

This is how the code would look like after simplifying it. It should be noted that leaving `success()` at the end of the test would lead to a test that can fail silently. We should probably add a method on `server` that asserts if it has been called `n` times.

```rust
mod support; // https://github.com/seanmonstar/reqwest/blob/master/tests/support/server.rs
use support as server;

#[tokio::test]
async fn hyper_test() {
    let server = server::http(move |req| async move {
        assert_eq!(req.method(), "POST");
        assert_eq!(req.headers()["Content-Type"], "application/json");
        assert_eq!(
            hyper::body::to_bytes(req).await.unwrap().as_ref(),
            b"{\"name\":\"ali\"}"
        );

        http::Response::builder()
            .header(http::header::CONTENT_TYPE, "application/json")
            .body("{\"got\": \"name\", \"status\": \"ok\"}".into())
            .unwrap()
    });

    get_command()
        .arg("--print=b")
        .arg("--pretty=format")
        .arg("post")
        .arg(server.addr().to_string())
        .arg("name=ali")
        .assert()
        .success();
}
```
