### ISSUE TITLE
Expand tilde to home directory

### ISSUE THREAD

**Issue by haakonn** [ducaale/xh#189]
On Linux, the following works in HTPPie:

`http -f POST example.com/files @~/.profile`

But when attempting `xh -f POST example.com/files @~/.profile`, I get "xh: error: No such file or directory (os error 2)".

It turns out the tilde is not being interpreted, and it works if I expand it manually: `xh -f POST example.com/files @/home/user/.profile`. I can also use `$HOME` so that my shell expands it for me, but I much prefer the brevity of `~`.

**Comment by blyxxyz** [comment]
Good catch. It seems HTTPie also expands paths to sessions (but not session names).

To match HTTPie (`os.path.expanduser`) we should ideally have a solution that also expands `~username/...`.

**Comment by ducaale** [comment]
We could try using the [home_dir crate](https://docs.rs/home-dir/0.1.0/home_dir/) or any of the crates listed [here](https://blog.liw.fi/posts/2021/10/12/tilde-expansion-crates/).

**Comment by blyxxyz** [comment]
`home_dir` is Unix-only, so it's not ideal.

I don't really like any of the libraries in the list. Maybe for now we could just have a function that checks if the first [component](https://doc.rust-lang.org/std/path/struct.Path.html#method.components) is `~` and replaces it by `dirs::home_dir()` if so. That gets us most of what we need.

I did some similar work for uutils recently, so maybe I'll try to write a new crate later.

**Comment by ducaale** [comment]
A fix for this has been included in the newly released xh v0.15.0.
