### ISSUE TITLE
The demo animation is old

### ISSUE THREAD

**Issue by sorairolake** [ducaale/xh#205]
The output of the download mode has changed, but this is not reflected in [the demo animation](https://github.com/ducaale/xh/blob/201ddf47e5cb2a893e96781240d84d6b257dd5c9/assets/xh-demo.gif).

See: #119, #192

**Comment by ducaale** [comment]
Before updating the demo animation, I would like to tweak how the `elapsed time` is displayed. While `humantime` formatting is helpful in longer durations, it becomes verbose for shorter durations. 
 
```sh
$ xh httpbin.org/json -d > /dev/null
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Length: 429
Content-Type: application/json
Date: Sun, 09 Jan 2022 12:33:30 GMT
Server: gunicorn/19.9.0

Downloading 429B to "<stdout>"
Done. 429B in 16ms 141us 500ns (25.95KiB/s)

$ http httpbin.org/json -d > /dev/null
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Length: 429
Content-Type: application/json
Date: Sun, 09 Jan 2022 12:34:25 GMT
Server: gunicorn/19.9.0

Downloading 429.00 B to "<stdout>"
Done. 429.00 B in 0.00246s (169.96 kB/s)
```

Notice how xh formats `elapsed time` as `16ms 141us 500ns` and HTTPie displays it as `0.00246s`.

**Comment by sorairolake** [comment]
@ducaale Was it solved by #236?

**Comment by ducaale** [comment]
Yup, the only thing remaining is to record a new asciinema demo and convert it to a `.gif` file. 

Fortunately, I have an AutoHotkey script prepared this time, so the recording shouldn't be as painful as last time.

**Comment by ducaale** [comment]
The Demo animation has been updated in the `develop` branch. Thanks for the reminder @sorairolake!
