### ISSUE TITLE
Oneliner to install xh under Windows

### ISSUE THREAD

**Issue by henno** [ducaale/xh#219]
Httpie is much more complicated  to install under Windows than under Linux and Mac. Xh is somewhat easier but it still involves many manual steps compared to Linux and Mac (downloading the release, extracting it, putting the executable into PATH, installing the VS C++ Redistributable).

It would be super awesome if there was a oneliner command to install under Windows as well.

**Comment by ChrisK-0** [comment]
Made a Powershell file and added a one-liner to readme for the repository. If it gets accepted then try that.
#220

**Comment by ducaale** [comment]
We can work around the `VS C++ Redistributable` issue by statically linking the C runtime. See https://github.com/BurntSushi/ripgrep/pull/1613 for an example.

As for the remaining installation steps, have you tried using [Scoop package manager](https://scoop.sh/) to install xh instead? Most of the well-known rust-based CLI tools are available in the [Main bucket](https://github.com/ScoopInstaller/Main/tree/master/bucket) of Scoop.

**Comment by ducaale** [comment]
Thanks to @ChrisK-0, you can now install xh by issuing the following command in PowerShell:
```
iwr -useb https://raw.githubusercontent.com/ducaale/xh/master/install.ps1 | iex
```

We have also started to statically link the C runtime, starting with xh v0.15.0. That should remove the need for installing `VS C++ Redistributable`.
