### ISSUE TITLE
Can't use --proxy with localhost

### ISSUE THREAD

**Issue by slavaGanzin** [ducaale/xh#223]
Hi, awesome project.

I'm trying to use --proxy but:
```
$ xh --proxy http://127.0.0.1:8899  "https://checkip.amazonaws.com" 
error: Invalid value for '--proxy <PROTOCOL:URL>...': Invalid proxy URL '//127.0.0.1:8899' for protocol 'http': relative URL without a base

$ xh --proxy http://localhost:8899  "https://checkip.amazonaws.com"
error: Invalid value for '--proxy <PROTOCOL:URL>...': Invalid proxy URL '//localhost:8899' for protocol 'http': relative URL without a base
```
So what i'm doing wrong?

Curl works as it should:
```
 curl -x 127.0.0.1:8899  "https://checkip.amazonaws.com"
 
 ```

**Comment by blyxxyz** [comment]
That error message is pretty unhelpful, yeah.

You're supposed to write `--proxy all:http://localhost:8899` or `--proxy https:http://localhost:8899`.

See the docs (`xh help`):
```
        --proxy <PROTOCOL:URL>...
            Use a proxy for a protocol. For example: `--proxy
            https:http://proxy.host:8080`.
            
            PROTOCOL can be `http`, `https` or `all`.
            
            If your proxy requires credentials, put them in the URL, like so:
            `--proxy http:socks5://user:password@proxy.host:8000`.
            
            You can specify proxies for multiple protocols by repeating this
            option.
            
            The environment variables `http_proxy` and `https_proxy` can also be
            used, but are completely ignored if --proxy is passed.
```

I notice we handle this differently from HTTPie. I believe HTTPie interprets it as proxying `http` through `//127.0.0.1:8899`, and so it doesn't give an error. But that's confusing and I don't think we should mimic it. If the argument looks like a stand-alone URL I think we should interpret it as being for `all:`. That would make your attempted command work.

**Comment by slavaGanzin** [comment]
@blyxxyz Thanks for explanation

**Comment by im-n1** [comment]
Just bumped into similar issue where I cannot spicify proxy address as IP addess

```
~ xh --proxy "http:192.168.88.10:8080" http://google.com
error: Invalid value "http:192.168.88.10:8080" for '--proxy <PROTOCOL:URL>': Invalid proxy URL '192.168.88.10:8080' for protocol 'http': relative URL without a base

For more information try --help
```

If I switch `192.168.88.10` for `localhost` it works.

**Comment by ducaale** [comment]
@im-n1 I think the proxy address should be a fully qualified URL e.g `xh --proxy "http:http://192.168.88.10:8080" http://google.com`
