### ISSUE TITLE
Add support for Termux

### ISSUE THREAD

**Issue by ducaale** [ducaale/xh#227]
Once reqwest adds support [passing custom config to trust-dns-resolver](https://github.com/seanmonstar/reqwest/pull/900), we should be able to modify the path to system DNS configuration from `/etc/resolv.conf` to `/data/data/com.termux/files/user/etc/resolv.conf`.

In the meantime, users can run `termux-chroot` to make  `/etc/resolv.conf` available for xh.

**Comment by blyxxyz** [comment]
Termux actually packages xh already, and it works on my phone: https://github.com/termux/termux-packages/blob/master/packages/xh/build.sh

I'm guessing the magic happens in `termux_setup_rust` but I didn't dig deeper.

**Comment by ducaale** [comment]
At first, I thought it had to do something with `armv7-linux-androideabi`, but no. I just downloaded `xh-v0.15.0-aarch64-unknown-linux-musl` on termux and didn't encounter any `/etc/resolv.conf` related issues. I wonder why I had issues before🤔.
