### ISSUE TITLE
Difference in response Content-Type compared to curl

### ISSUE THREAD

**Issue by victorz** [ducaale/xh#229]
I've noticed a difference in response Content-Type between curl and xh for some reason, but I don't know how to debug it better than this. I'm trying to fetch weather info using xh (xhs), and when I use curl I get a text/plain response, which is what I want, but when I use xhs I get a text/html response.

```
~ % xhs -h 'wttr.in/Umea?T0'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Wed, 02 Feb 2022 10:59:05 GMT
Server: nginx/1.10.3
Transfer-Encoding: chunked
~ % curl 'https://wttr.in/Umea?T0' -D - -so /dev/null
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Wed, 02 Feb 2022 10:59:09 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 180
Connection: keep-alive
Access-Control-Allow-Origin: *
```

I even tried to use xhs's translation to a curl command, but I still get a text/plain response from curl as opposed to with xhs:

```
~ % xhs -h 'wttr.in/Umea?T0' --curl
curl -I -X GET 'https://wttr.in/Umea?T0'
~ % curl -I -X GET 'https://wttr.in/Umea?T0'
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Wed, 02 Feb 2022 11:01:42 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 180
Connection: keep-alive
Access-Control-Allow-Origin: *
```

How can I tell xhs to make the request accept only a text/plain response? I've tried appending `Accept:text/plain` to the end of my command with no success.

Is this a bug? :man_shrugging: Thanks for any help regarding this!

**Comment by blyxxyz** [comment]
wttr.in looks at the user agent to determine whether to send a plain text response. curl is treated specially, xh is not.

It works if you pretend to be curl by setting a different user agent:
```console
$ xhs 'wttr.in/Umea?T0' User-Agent:curl
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 180
Content-Type: text/plain; charset=utf-8
Date: Wed, 02 Feb 2022 11:51:09 GMT
Server: nginx/1.10.3

Weather report: Umea

   _`/"".-.     Light snow
    ,\_(   ).   -10(-16) °C    
     /(___(__)  ↘ 7 km/h       
       *  *  *  3 km           
      *  *  *   0.1 mm         
```
It should also work if `xh` were added to [this list](https://github.com/chubin/wttr.in/blob/8bdc54bb7097badbb2bfb9867ccaaa42b94a6636/cmd/srv.go#L20).

**Comment by victorz** [comment]
I see, brilliant, thanks so much! :+1: :heart:
