### ISSUE TITLE
Update Clap to v3.2

### ISSUE THREAD

**Issue by ducaale** [ducaale/xh#262]
~~n anticipation of the next major version, Clap v3.2 deprecated many existing APIs. Therefore, It would be beneficial for us to update early so we can provide early feedback regarding the new APIs.~~

See https://epage.github.io/blog/2022/06/clap-32-last-call-before-40/

**Update**: Clap v4 has been released, see https://epage.github.io/blog/2022/09/clap4/

**Comment by gautamprikshit1** [comment]
Would you like to update to clap v4?

**Comment by ducaale** [comment]
@gautamprikshit1 Unfortunately, clap v4 requires rust 1.64 which is too high for us at the moment. We might reconsider raising the MSRV once reqwest or another essential dependency raises their MSRV.

**Comment by ducaale** [comment]
The MSRV has been raised to 1.64, so we should be able to upgrade clap to v4 as soon as https://github.com/ducaale/xh/pull/269 is merged.

**Comment by gautamprikshit1** [comment]
Please let me know when clap 3 PR is merged

**Comment by ducaale** [comment]
Thanks @gautamprikshit1 - There were a lot of moving parts so I went ahead and updated Clap to v4.0. However, you can still help us with upgrading to v4.3 and that would be greatly appreciated.

**Comment by gautamprikshit1** [comment]
It might take a while as I already have another issue assigned in other project for this weekend, next weekend for sure
