### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by sorairolake** [ducaale/xh#298]
The dependencies should be as the latest as possible (considering the MSRV).

**Comment by ducaale** [comment]
Note that we can raise the MSRV to 1.56 once the next reqwest version with HTTPS IP address support is released (see recent activity in webpki fork by rustls https://github.com/rustls/webpki).

**Comment by ducaale** [comment]
**Update**: MSRV has been raised to 1.64 as a result of upgrading reqwest to v0.11.18
