### ISSUE TITLE
Support upload file from shared network path (UNC)

### ISSUE THREAD

**Issue by Ben-Mack** [ducaale/xh#305]
Currently xh return error when upload file from UNC path on Windows:

```
xh httpbin.org/post --form file@"\\server\test\a.txt"
xh: error: The system cannot find the path specified. (os error 3)
```

Please support file uploading from shared network path.

P/s: Thanks for creating and open source this product! 
I've been looking for curl alternative for a while because curl does not support upload file with unicode filename.
Tried HTTPie but it's not portable. Luckily I found this tool which does support file with non-latin name and swiftly support unicode characters in form (unlike curl). But it doesn't support UNC path so I can't implement this tool into our product yet. I'm really looking forward to UNC path support.

**Comment by ducaale** [comment]
HTTPie and xh use the backslash to escape special characters e.g request-item separators. This means you will need double backslashes to get the UNC path to work

```sh
$ xh httpbin.org/post --form file@"\\\\wsl.localhost\\Ubuntu\\home\\ducaale\\xh\\Cargo.toml"
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 4116
Content-Type: application/json
Date: Tue, 07 Feb 2023 23:06:27 GMT
Server: gunicorn/19.9.0

# response body omitted
```

**Comment by ducaale** [comment]
Closing this issue since xh already has UNC path support.
