### ISSUE TITLE
Make JSON indentation level configurable (e.g. 2 or 4 spaces)

### ISSUE THREAD

**Issue by Logarithmus** [ducaale/xh#316]
Currently 4 spaces are hardcoded. But I prefer 2 spaces, as it's better for deeply nested JSON and allows it to better fit into terminal width.

**Comment by ducaale** [comment]
HTTPie has the [`--format-options`](https://httpie.io/docs/cli/format-options) flag that can be used to configure JSON indentation e.g

```sh
# Note that options could be specified in a config file.
# See xh's manpage or refer to https://httpie.io/docs/cli/configurable-options
$ http --format-options json.indent:2 httpbingo.org/json
```

Would you be interested in opening a PR for this feature?

**Comment by Logarithmus** [comment]
yeah, I'm looking into doing it on weekend, hopefully.
