### ISSUE TITLE
Make appearances of the progress bar closer to HTTPie

### ISSUE THREAD

**Issue by sorairolake** [ducaale/xh#326]
Run `http -d "https://ftp.jaist.ac.jp/pub/Linux/ArchLinux/iso/2023.09.01/archlinux-2023.09.01-x86_64.iso"`:

![HTTPie's progress bar](https://github.com/ducaale/xh/assets/48999343/4d956614-1c1f-47cf-802a-1ad69d9ebcdf)

Run `xh -d "https://ftp.jaist.ac.jp/pub/Linux/ArchLinux/iso/2023.09.01/archlinux-2023.09.01-x86_64.iso"`:

![xh's progress bar](https://github.com/ducaale/xh/assets/48999343/91946187-e3c8-4b71-b608-8d79e88603d9)

Since the tick character is already Unicode, so I don't think there will be any problem if the progress characters is also Unicode.

Version:

```sh
$ xh -V
xh 0.18.0
$ http --version
3.2.1
```

**Comment by ducaale** [comment]
Can we close this in favour of https://github.com/ducaale/xh/issues/255? thanks
