### ISSUE TITLE
Equivalent command to curl -d

### ISSUE THREAD

**Issue by nkh** [ducaale/xh#341]
Hi, I'm trying to replace he following *curl* command with an *xh* command.

```
curl localhost:4266 -d "put(x)" 
```

I've tried 

```
xh :4266 --raw 'put(x)'
```

but I get

```
xh: error: error sending request for url (http://localhost:4266/): connection closed before message completed

Caused by:
    connection closed before message completed
```

while curl succeeds.

**Comment by ducaale** [comment]
The only difference between the two commands I could think of is the content-type header. Could you try using the `--form` option to set the content-type to `application/x-www-form-urlencoded`?

```
xh :4266 --raw 'put(x)' --form
```

**Comment by nkh** [comment]
@ducaale that gives the same result

FYI: the sequence is send to ```fzf --listen 4266```

**Comment by blyxxyz** [comment]
fzf implements [its own HTTP server](https://github.com/junegunn/fzf/blob/e8b34cb00d4446e69e7af3d31eafcf76747d34c7/src/server.go#L123) that seems to have some odd behavior even if I just talk to it with netcat.

The request notably *does* work (on my machine). fzf does what it's told. But xh doesn't like it when fzf unceremoniously closes the connection.

This is almost certainly a fzf bug, though a nitpicky one that they may or may not be interested in fixing.

**Comment by nkh** [comment]
@blyxxyz It indeed does do what it's told to do.

I'll report it to the fzf project.

**Comment by blyxxyz** [comment]
OK, I found the problem. fzf's response is missing a CRLF after the header section. It should send `HTTP/1.1 200 OK\r\n\r\n` but it only sends `HTTP/1.1 200 OK\r\n`. Most HTTP implementations don't seem to mind but hyper is very pedantic.

I've submitted a PR: https://github.com/junegunn/fzf/pull/3542
