### ISSUE TITLE
Seeking Discussion Forum

### ISSUE THREAD

**Issue by apreifsteck** [ducaale/xh#373]
Is there a discord or similar tool that you all use to communicate more informally about xh? I'd like to contribute, but I'd like to discuss some of the ideas I had before putting together a proposal or the like. What is the best way to communicate with xh's maintainers?

**Comment by ducaale** [comment]
Hey @apreifsteck, all discussions occur in GitHub issues so they can be accessible for future reference. There are no strict rules, so feel free to open one for any ideas or guidance you need.

If you have questions related to Rust's networking ecosystem, I encourage you to join the Tokio Discord group: https://discord.com/invite/tokio.

**Comment by apreifsteck** [comment]
Sounds good, I'll open a separate issue with my question.
