### ISSUE TITLE
Encoded query strings are double encoded

### ISSUE THREAD

**Issue by nickpending** [ducaale/xh#384]
Using a query string with URL encoding results in xh double encoding the string.

b%61r becomes b%2561r

```
❯ xhs test.example.com "foo==b%61r" --offline
GET /?foo=b%2561r HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: test.example.com
User-Agent: xh/0.22.2
```

I'm not sure if this is intended or not, but if it is, it would be nice to have an option to suppress encoding.

**Comment by ducaale** [comment]
This is inline with HTTPie and also cURL's `--data-urlencode <name=content>` option.

You can opt out of the encoding by having the query as part of the URL:

```
$ xhs "test.example.com?foo==b%61r" --offline
GET /?foo==b%61r HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: test.example.com
User-Agent: xh/0.22.0
```

**Comment by nickpending** [comment]
Got it. Thanks for clarifying. I wasn't able to find this documented anywhere.
