### ISSUE TITLE
Feature request: Switch to `https://` protocol or ad `xhs` shortcut

### ISSUE THREAD

**Issue by markstos** [ducaale/xh#386]
Today, about 90% of the web uses `https`, but `httpie` while `xh` defaults to the `http` protocol if now protocol is provided (like http:// or https://).

I think it's time to flip the default to match the modern web, even if it's a breaking change.

Or you could go the route of `httpie` and ship a second binary. They shipped `https`. You could ship `xhs`. 

But given that this is now a 90/10 split and not close to a 50/50 split, I think it makes more sense to change the default.

**Comment by blyxxyz** [comment]
[We already ship an `xhs` symlink with that behavior!](https://github.com/ducaale/xh?tab=readme-ov-file#making-https-requests-by-default) You can also make an alias for `xh --https`.

Defaulting to it could be pretty disruptive unfortunately. Most of the public web is on HTTPS as it should be, but I personally use xh a lot for testing local servers without TLS.

**Comment by markstos** [comment]
Thanks for fast reply.

I thought I had checked for `xhs` previously and didn't find it, but I see it there now. 

👍

**Comment by blyxxyz** [comment]
Chrome plans to switch to HTTPS by default for public sites only: https://security.googleblog.com/2025/10/https-by-default.html

(private sites being "local IP addresses like 192.168.0.1, single-label hostnames, and shortlinks like intranet/".)

That seems worth considering. Though it'd still be a little disruptive and unintuitive and finicky to implement.
