### ISSUE TITLE
Either remove or increase async

### ISSUE THREAD

**Issue by blyxxyz** [ducaale/xh#39]
`ht` uses async, but it uses it inconsistently and I'm not sure that it needs it.

Is it likely that it will start doing multiple requests at a time in the future? If so, then blocking APIs like `std::fs` should be avoided. If not, then maybe [reqwest's blocking API](https://docs.rs/reqwest/0.11.0/reqwest/blocking/index.html) would be easier to use.

**Comment by ducaale** [comment]
reqwest's blocking API is indeed simpler and `ht` was initially using that. Unfortunately, it does not offer an [API](https://docs.rs/reqwest/0.11.0/reqwest/struct.Response.html#method.chunk) for incrementally fetching a streaming response.

**Comment by blyxxyz** [comment]
It supports that through [`io::Read`](https://docs.rs/reqwest/0.11.0/reqwest/blocking/struct.Response.html#impl-Read).

I'm working on an implementation. It adds some interesting possibilities. For example, [you can wrap a `ProgressBar` around a reader](https://docs.rs/indicatif/0.15.0/indicatif/struct.ProgressBar.html#method.wrap_read).
