### ISSUE TITLE
document `<auth>` strategies

### ISSUE THREAD

**Issue by andyczerwonka** [ducaale/xh#40]
The document suggest an `auth` argument, but I'm not sure what they are.

**Comment by ducaale** [comment]
I will temporarily write this here until it gets added to `README.md`.

Auth could take one of the following:
* when `auth-type` is `bearer` (default):
  * `token` (a shortcut for `authorization:bearer token`)
* when `auth-type` is `basic`
  * `username:password`
  * `username` (a password prompt will be displayed later)
  * `username:` for passwordless authentication

**Comment by ducaale** [comment]
_--auth_ flag is now documented. We also have [deprecated](https://github.com/ducaale/xh/pull/64) _--auth-type_ in favor of _--bearer_ flag for bearer authentication.
