### ISSUE TITLE
-h does not map to request type HEAD

### ISSUE THREAD

**Issue by SuperSandro2000** [ducaale/xh#50]
When doing ht -h it displays the help instead of doing a HEAD request.

**Comment by otaconix** [comment]
Just to be clear, `-h`/`--headers` does **not** result in httpie performing a `HEAD` request: it performs the request method you indicate, and prints only the response headers.

So, if you do a `POST` with the `-h` flag set, expect side effects :)

**Comment by ducaale** [comment]
Support for the `-h` flag was added by PR https://github.com/ducaale/ht/pull/42 and it should part of the next release.

**Comment by ducaale** [comment]
`xh` (formerly `ht`) v0.7.0 has been released which supports the _-h/--header_ flag 🎉
