### ISSUE TITLE
Replace --default-scheme

### ISSUE THREAD

**Issue by blyxxyz** [ducaale/xh#72]
The only useful use of `--default-scheme` is `--default-scheme=https` (`http` is the default, other schemes don't work). Maybe it should be replaced by a `--https` flag?

We could keep `--default-scheme` as a deprecated [hidden](https://docs.rs/clap/2.33.3/clap/struct.Arg.html#method.hidden) flag.

**Comment by ducaale** [comment]
Sounds good to me. I wonder if `auth-type` should also have been made hidden instead of removing it.
