### ISSUE TITLE
"--no-" variants of flags

### ISSUE THREAD

**Issue by blyxxyz** [ducaale/xh#84]
HTTPie lets you negate flags, e.g. `--no-check-status` cancels out `--check-status`. While [`argparse` has optional support for that](https://github.com/python/cpython/blob/3b4b2cf418707c79f96689e401e3c703c0fdd4d2/Lib/argparse.py#L856), HTTPie does it by [manually processing arguments `argparse` didn't recognize](https://github.com/httpie/httpie/blob/56c4ba17942fb6374cfa6f31954f3fab9061a21b/httpie/cli/argparser.py#L259) (plus a few [hardcoded cases](https://github.com/httpie/httpie/blob/56c4ba17942fb6374cfa6f31954f3fab9061a21b/httpie/cli/definition.py#L269)).

`clap` doesn't support this, but there's an issue for it (clap-rs/clap#815). It also has an [escape hatch](https://docs.rs/clap/2.33.3/clap/enum.AppSettings.html#variant.AllowExternalSubcommands) for looking at unknown arguments, but I don't know exactly how powerful it is, and I'm worried it would degrade the usual error message.

A downside of HTTPie's current approach (and probably of the escape hatch approach for `clap`) is that the order of the flags doesn't matter. Normally the last flag counts, so `--form --json` works like `--json` and `--json --form` like `--form`, but `--no-check-status` always overrides `--check-status`, even if it comes first. But that's acceptable, since the typical usage would be to add `--no-check-status` after an alias that includes `--check-status`, and the opposite wouldn't come up because there's little reason to use `--no-check-status` in an alias.

If this is added to `clap` it might take a long time before it's usable in `xh`. It'd land in version 3.0.0, and then after that we might have to wait for `structopt` to support it (or maybe switch to `clap_derive`).

**Comment by ducaale** [comment]
I think HTTPie current behavior could be emulated (although a bit tedious) with something like this https://github.com/TeXitoi/structopt/issues/320#issuecomment-570988032

```rust
#[derive(StructOpt)]
struct Opt {
    #[structopt(long, help="enabled debug (disable with --no-debug)")]
    pub debug: bool,
    #[structopt(long, overrides_with="debug", hidden=true)]
    pub _no_debug: bool
}
```
