### ISSUE TITLE
Do not display special characters in dos prompt

### ISSUE THREAD

**Issue by anborg** [ducaale/xh#98]
Expected: Not to display special characters when displaying json 

Actual: Displays special characters.

![image](https://user-images.githubusercontent.com/56970398/110866913-e5139000-8293-11eb-8319-9948e1decd56.png)

No special characters with curl

![image](https://user-images.githubusercontent.com/56970398/110866960-fbb9e700-8293-11eb-82d3-ce4e9bb7cea6.png)

**Comment by blyxxyz** [comment]
Ah, those are the colors. We should look for a way to detect when the terminal doesn't support them.

As a workaround you can disable colors completely by adding `--pretty format`.

Which version of Windows are you using? In newer versions ANSI colors should be turned on by default, I think. Maybe the instructions under "Enabling ANSI colors in older versions of Windows" on https://ss64.com/nt/syntax-ansi.html can fix it?

**Comment by ducaale** [comment]
Colors can also be disabled via the [`no_color`](https://no-color.org/) flag.
```sh
# temporarily set the env variable
set no_color=1   

# permenantly set the env variable
setx no_color=1  
```

You could also use [Windows Terminal](https://www.microsoft.com/en-gb/p/windows-terminal/9n0dx20hk701?rtc=1) which support ANSI colors

<img width="806" alt="Screenshot 2021-03-11 233110" src="https://user-images.githubusercontent.com/16341131/110869219-e9ef3880-82c1-11eb-8438-fea6529b6786.png">

**Comment by anborg** [comment]
Interesting.. 

Windows Terminal, by default opened PoweShell tab which spewed error. Later I opened Dos inside it, no more special characters.  Looks like I need to find a better terminal :)


Power shell ...

![image](https://user-images.githubusercontent.com/56970398/110872972-cd8dd480-829e-11eb-9777-7fa5780524fd.png)


DOS... prompt?

![image](https://user-images.githubusercontent.com/56970398/110873015-dda5b400-829e-11eb-9fb2-c246d441dbdd.png)

**Comment by blyxxyz** [comment]
I think https://github.com/BurntSushi/termcolor might do the trick.

[ripgrep](https://github.com/BurntSushi/ripgrep) uses it, so I'd be interested to know if it prints colors in the outdated DOS prompt that xh messes up. (If it just switches off colors then that would be progress too.)

**Comment by ducaale** [comment]
It seems ripgrep is able to output colors correctly in the old Windows Console

<img width="674" alt="Screenshot 2021-03-12 180229" src="https://user-images.githubusercontent.com/16341131/110979917-2b80f180-835d-11eb-8a9b-b3ab9b2d7072.png">

-------------------------------------------

>Windows Terminal, by default opened PoweShell tab which spewed error.

Not sure why but I am able to run the `xh` that I installed with scoop in Powershell

<img width="806" alt="Screenshot 2021-03-12 180653" src="https://user-images.githubusercontent.com/16341131/110980566-e0b3a980-835d-11eb-9ae5-793648906b02.png">

**Comment by ducaale** [comment]
Hmm, this is interesting. So it seems colors work when `xh` is run via cargo

<img width="674" alt="Screenshot 2021-03-12 232419" src="https://user-images.githubusercontent.com/16341131/111008996-55044200-838a-11eb-903f-20f50ab1a245.png">

But not when the executable is run directly

<img width="674" alt="Screenshot 2021-03-12 233327" src="https://user-images.githubusercontent.com/16341131/111009401-6e59be00-838b-11eb-9d7d-26c5d79c88de.png">

**Comment by ducaale** [comment]
xh v0.9.1 has been released which improves color support in windows 🎉
